### ISSUE TITLE
com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.grpc.netty.shaded.io.netty.util.internal.logging.Log4J2Logger

### ISSUE THREAD

**Issue by mklueh** [GoogleCloudPlatform/native-image-support-java#306]
I'm running into this error when using `'com.google.firebase:firebase-admin:7.3.0'`

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: io.grpc.netty.shaded.io.netty.util.internal.logging.Log4J2Logger. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing io.grpc.netty.shaded.io.netty.util.internal.logging.Log4J2LoggerFactory.newInstance(Log4J2LoggerFactory.java:33)
Call path from entry point to io.grpc.netty.shaded.io.netty.util.internal.logging.Log4J2LoggerFactory.newInstance(String): 
	no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.apache.log4j.Logger. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
	at parsing io.grpc.netty.shaded.io.netty.util.internal.logging.Log4JLoggerFactory.newInstance(Log4JLoggerFactory.java:38)
Call path from entry point to io.grpc.netty.shaded.io.netty.util.internal.logging.Log4JLoggerFactory.newInstance(String): 
	no path found from entry point to target method


	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:129)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:756)
	... 6 more
Error: Image build request failed with exit status 1

> Task quarkusBuild FAILED
23 actionable tasks: 1 executed, 22 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task 'quarkusBuild'.
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
  	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:250)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
  	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
  	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
  	at java.base/java.lang.Thread.run(Thread.java:833)
  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
  Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:386)
  	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:229)
  	... 11 more


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 9s
18:34:04: Execution finished 'build -Dquarkus.package.type=native -Dquarkus.native.container-build=true'.

```

Is this supposed to be covered by this library as well?

**Comment by suztomo** [comment]
Thank you for reporting the issue. What version of native-image-support-java and log4J do you use?

I haven't tried to reproduce the problem myself but would you be willing to share a small project to reproduce the problem?

Memo: `com.google.firebase:firebase-admin:7.3.0` was released May 2021.

**Comment by mklueh** [comment]
I'm using the latest version of native-image-support together with Quarkus 2.6.2 and just the `@Slf4j` annotation of Lombok. To be honest, I'm not exactly sure what is used under the hood, but for my understanding, it is proxied through JBoss logging by Quarkus, so no log4j is used at all.

**Comment by suztomo** [comment]
Yes, please let us know the result with the latest. Also looking forward to a project to reproduce the issue.

(The latest native-image-support is `com.google.cloud:native-image-support:0.10.0`, released in November 2021)

**Comment by mklueh** [comment]
Thanks. It seems the error is gone with the latest version of firebase admin

**Comment by suztomo** [comment]
Glad to hear that. Thank you for update.
