### ISSUE TITLE
Substition: com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion.toString() conflicts with previously registered

### ISSUE THREAD

**Issue by mklueh** [GoogleCloudPlatform/native-image-support-java#344]
Hello,

I'm using these two versions of the firebase admin SDK and the native-image-support-java library

```
    api 'com.google.firebase:firebase-admin:8.1.0'
    api 'com.google.cloud:native-image-support:0.10.0'
```

but getting the following error:

```
Error: Substition: com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion.toString() conflicts with previously registered: com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion.toString()
com.oracle.svm.core.util.UserError$UserException: Substition: com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion.toString() conflicts with previously registered: com.google.api.client.googleapis.services.AbstractGoogleClientRequest$ApiClientVersion.toString()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:101)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:836)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:389)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:340)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:310)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:266)
	at com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:889)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:816)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:534)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:494)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:426)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:587)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:126)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:617)
```

What am I missing?

**Comment by mklueh** [comment]
I didn't notice that the latest version of this library is 0.12.6, as it says 0.10.0 on the readme page. It seems with that version the error is gone
