### ISSUE TITLE
grpc-netty-shaded substitution error when building (Micronaut/Gradle)

### ISSUE THREAD

**Issue by jamesrowe08** [GoogleCloudPlatform/native-image-support-java#405]
Using micronaut 3.5.0, google-cloud-pubsub:1.118.0, native-image-support:0.14.1 and when building using native image:

Build fails with:

`#11 6.390 Error: Substition: io.grpc.netty.shaded.io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(String) conflicts with previously registered: io.grpc.netty.shaded.io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(String)
#11 6.391 com.oracle.svm.core.util.UserError$UserException: Substition: io.grpc.netty.shaded.io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(String) conflicts with previously registered: io.grpc.netty.shaded.io.netty.util.internal.logging.InternalLoggerFactory.newDefaultFactory(String)
#11 6.391       at com.oracle.svm.core.util.UserError.abort(UserError.java:72)
#11 6.391       at com.oracle.svm.core.util.UserError.guarantee(UserError.java:96)
#11 6.391       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:849)
#11 6.391       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:402)
#11 6.391       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:353)
#11 6.391       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:323)
#11 6.391       at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:279)
#11 6.391       at com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:933)
#11 6.391       at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:846)
#11 6.391       at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:555)
#11 6.391       at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:515)
#11 6.391       at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
#11 6.391       at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
#11 6.391       at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
#11 6.391       at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:615)`

**Comment by mpeddada1** [comment]
Hello @jamesrowe08! The client libraries come with the native image configurations built-in as of `libraries-bom 25.4.0`. You don't need the `native-image-support` dependency anymore.
